spring.application.name=circulation-service

spring.datasource.url=jdbc:postgresql://localhost:5432/circulation_db
spring.datasource.username=concord
spring.datasource.password=concord

spring.jpa.hibernate.ddl-auto=update

server.port=8082

catalog.service.url=http://localhost:8081
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/concord/protocol/openid-connect/certs