spring.application.name=circulation-service
spring.datasource.url=jdbc:postgresql://localhost:5432/circulation_db
spring.datasource.username=concord
spring.datasource.password=concord
server.port=8082
